env:
  - NODE_VERSION=0.10
  - NODE_VERSION=0.11
# - NODE_VERSION=iojs
# not testing on iojs until dependencies support it

sudo: false

os:
  - osx
  - linux

install:
  - test $TRAVIS_OS_NAME = "osx" && brew install nvm && source $(brew --prefix nvm)/nvm.sh || test $TRAVIS_OS_NAME = "linux"
  - nvm install $NODE_VERSION
  - node --version
  - npm --version
  - npm install

script:
  - npm test

after_success: npm run coveralls

matrix:
  allow_failures:
    - os: osx
    - env: "NODE_VERSION=0.11"
  fast_finish: true

notifications:
  email: false
  slack:
    secure: R+TkavWRhREwc9shV6JYJ+YrrMdpaSB5iYlVVhtO4XjSJPtbsgFvg8aelELIfwUY/Lsl6dmUD8bhv1GxN4Bdui7igrGEzXqh+ziJSnPET0Apxyc2HFYzM3phQYwsESyFXGfx9PiegLQ6fcozZ75rio17YhPjT8//9jb5I9hue9g=
